version: '3.8'
services:
  monitor-app:
    build: .
    ports:
      - "8080:8080"
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
